# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: anbenqishi,github.io
date_format: "ordinal"
title: 胡言乱语
subtitle: "小小黑的个人空间"
description: "或有停留，随遇而安"
keywords: Linux, UDP, wujg
timezone: Asia/Shanghai
encoding: "utf-8"
port: 4001
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: wujg
organization: xmu
organization_url: www.xmu.end.cn
github_username: anbenqishi
location: Fuzhou, China
email: jiangui1987@gmail.com


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
#permalink: pretty
#paginate: 10
#exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
#anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: anbenqishi/anbenqishi.github.io
# fix warning
github: [metadata]

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: mzlogin
#    repo: blog-comments
#    oauth:
#        client_id: d2e1cbbd298958076462
#       client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: anbenqishi
    repo: anbenqishi.github.io
    clientID: 2d6dc1917951752a9ea0
    clientSecret: 2a4864a0264d77cf9af6ac1699cb5e14bf07ecd8
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
#    analytics_id: UA-80669434-1
