# Site settings
title: 所思及所想
email: xxx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a programmer wants to do something.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anbenqishi.github.io" # the base hostname & protocol for your site
twitter_username: anbenqishi
github_username:  anbenqishi

# Build settings
port: 4001
markdown: kramdown
highlighter: pygments
encoding: utf-8
